# Generated by Django 5.2.1 on 2025-11-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushiemcasa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDeFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')], unique=True, verbose_name='Dia da semana')),
                ('is_open', models.BooleanField(default=False, help_text='Marque se a loja está aberta neste dia.', verbose_name='Aberto?')),
                ('open_time', models.TimeField(blank=True, help_text='Formato: HH:MM', null=True, verbose_name='Horário de Abertura')),
                ('close_time', models.TimeField(blank=True, help_text='Formato: HH:MM', null=True, verbose_name='Horário de Fechamento')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'ordering': ['day_of_week'],
            },
        ),
    ]
