# Generated by Django 5.2.1 on 2025-10-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushiemcasa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date and Time'),
        ),
    ]
