# Generated by Django 5.2.1 on 2025-10-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushiemcasa', '0002_categoria_mensagemfeedback_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date and Time'),
        ),
    ]
