# Generated by Django 5.2.1 on 2025-11-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushiemcasa', '0002_horariodefuncionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
