# Generated by Django 5.2.6 on 2025-10-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sushiemcasa', '0002_categoria_mensagemfeedback_order_delivery_datetime_and_more'),
        ('sushiemcasa', '0002_order_delivery_datetime'),
        ('sushiemcasa', '0004_alter_order_status'),
    ]

    operations = [
    ]
