# Generated by Django 5.2.6 on 2025-10-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushiemcasa', '0005_merge_20251022_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pendente'), ('In Preparation', 'Em preparo'), ('Out for Delivery', 'A caminho'), ('Delivered', 'Entregue'), ('Cancelled', 'Cancelado')], default='Pending', max_length=20),
        ),
    ]
