# Generated by Django 5.2.1 on 2026-01-30 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushiemcasa', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pendente'), ('Accepted', 'Aceito'), ('In Preparation', 'Em preparo'), ('Out for Delivery', 'Pronto para retirada'), ('Delivered', 'Entregue'), ('Cancelled', 'Cancelado')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BannerPromocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da Promoção')),
                ('descricao', models.TextField(verbose_name='Descrição Curta')),
                ('imagem', models.ImageField(upload_to='banners/', verbose_name='Imagem do Banner (Recomendado: 1200x400)')),
                ('preco_promocional', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço de Oferta')),
                ('preco_antigo', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Preço Riscado')),
                ('ativo', models.BooleanField(default=True, verbose_name='Banner Ativo?')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('produto_vinculado', models.ForeignKey(blank=True, help_text='Selecione o produto que será adicionado ao carrinho quando clicarem no banner.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sushiemcasa.produto', verbose_name='Produto para Venda')),
            ],
            options={
                'verbose_name': 'Banner Promocional',
                'verbose_name_plural': 'Banners Promocionais',
                'ordering': ['ordem'],
            },
        ),
    ]
